# Fail on warnings - also for files referenced in subdirs
# -Werror can be disabled for specific files using:
# CFLAGS_<file.o> := -Wno-error
subdir-ccflags-y := -Werror

# clang's preprocessor will emit -Wunicode warnings for some .macro's because
# they use '\u' as arguments.
# This disables that warning for both gcc and clang, as Unicode characters are
# not used in MIPS assembly code.
subdir-asflags-y := -Wno-unicode

# platform specific definitions
include arch/mips/Kbuild.platforms
obj-y := $(platform-y)

# make clean traverses $(obj-) without having included .config, so
# everything ends up here
obj- := $(platform-)

# mips object files
# The object files are linked as core-y files would be linked

obj-y += kernel/
obj-y += mm/
obj-y += net/
obj-y += vdso/

ifdef CONFIG_KVM
obj-y += kvm/
endif
